# Generated by Django 3.2 on 2021-05-01 22:08

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tipsyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Outdoor Seating/Patio', 'Outdoor Seating/Patio'), ('Pet Friendly', 'Pet Friendly'), ('Appetizers', 'Appetizers'), ('Large Variety of Draft Beers', 'Large Variety of Draft Beers'), ('Cider Options', 'Cider Options'), ('Wine Options', 'Wine Options'), ('Trivia', 'Trivia'), ('Live Entertainment', 'Live Entertainment'), ('Knowledgable Staff', 'Knowledgable Staff'), ('Flea Markets', 'Flea Markets'), ('Beer Options', 'Beer Options'), ('Food Trucks', 'Food Trucks'), ('MUST VISIT!', 'MUST VISIT!'), ('Friendly Staff', 'Friendly Staff'), ('Indoor Seating', 'Indoor Seating'), ('Cool Vibes', 'Cool Vibes'), ('Hazy IPAs', 'Hazy IPAs'), ('NE IPAs', 'NE IPAs'), ('Sours/Goses', 'Sours/Goses'), ('Saisons', 'Saisons'), ('Lagers', 'Lagers'), ('Amber/Red Ales', 'Amber/Red Ales')], max_length=297, null=True),
        ),
    ]
