# Generated by Django 3.2 on 2021-04-28 16:36

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tipsyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Outside Seating/Patio'), ('2', 'Pet Friendly'), ('3', 'Great Appetizers'), ('4', 'Large Variety of Draft Beers')], max_length=7, null=True),
        ),
    ]
