# Generated by Django 3.2 on 2021-04-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipsyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=100)),
                ('venue_type', models.CharField(choices=[('br', 'Brewery'), ('ds', 'Distillery'), ('wn', 'Winery')], default='br', max_length=30)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('hours_of_operation', models.TextField(max_length=300)),
                ('web_url', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_num', models.CharField(max_length=10)),
                ('street_address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('prof_pic', models.URLField(max_length=300)),
                ('followers_num', models.IntegerField(default=0)),
                ('tags', models.CharField(blank=True, choices=[('1', 'Outside Seating/Patio'), ('2', 'Pet Friendly'), ('3', 'Great Appetizers'), ('4', 'Large Variety of Draft Beers')], max_length=103, null=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['join_date'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='bio_text',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='Durham', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='prof_pic',
            field=models.URLField(default='https://images-na.ssl-images-amazon.com/images/I/51Pt-epHb2L._AC_SX466_.jpg', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='star_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='NC', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='users_following_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='venues_following_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='venues_following_list',
            field=models.ManyToManyField(blank=True, related_name='venue_follows', to='tipsyapp.Venue'),
        ),
    ]
