# Generated by Django 3.2 on 2021-04-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipsyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fb_link',
            field=models.URLField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='insta_handle',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='fb_link',
            field=models.URLField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='insta_handle',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='phone_num',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='zip',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
