# Generated by Django 3.2 on 2021-04-21 15:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tipsyapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='id',
        ),
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='venue_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, null=True),
        ),
    ]
