# Generated by Django 3.2 on 2021-04-21 15:33

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    User = apps.get_model('tipsyapp', 'User')
    for row in User.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])
        
    Venue = apps.get_model('tipsyapp', 'Venue')
    for row in Venue.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

    Post = apps.get_model('tipsyapp', 'Post')
    for row in Post.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('tipsyapp', '0002_auto_20210421_1148'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
