# Generated by Django 3.2 on 2021-04-28 16:58

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tipsyapp', '0002_alter_venue_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Outdoor Seating/Patio'), ('2', 'Pet Friendly'), ('3', 'Appetizers'), ('4', 'Large Variety of Draft Beers'), ('5', 'Cider Options'), ('6', 'Wine Options'), ('7', 'Trivia'), ('8', 'Live Entertainment'), ('9', 'Knowledgable Staff'), ('10', 'Flea Markets'), ('11', 'Beer Options'), ('12', 'Food Trucks'), ('13', 'MUST VISIT!'), ('14', 'Friendly Staff'), ('15', 'Indoor Seating'), ('16', 'Cool Vibes'), ('17', 'Hazy IPAs'), ('18', 'NE IPAs'), ('19', 'Sours/Goses'), ('20', 'Saisons'), ('21', 'Lagers'), ('22', 'Amber/Red Ales')], max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_type',
            field=models.CharField(choices=[('Brewery', 'Brewery'), ('Distillery', 'Distillery'), ('Winery', 'Winery')], default='brewery', max_length=30),
        ),
    ]
