# Generated by Django 3.2 on 2021-04-28 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipsyapp', '0002_alter_checkin_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkin',
            options={'ordering': ['-checkin_time']},
        ),
    ]
