# Generated by Django 3.2 on 2021-04-22 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipsyapp', '0002_auto_20210421_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='posted_to',
            new_name='posted_to_venue',
        ),
        migrations.AddField(
            model_name='post',
            name='post_likers',
            field=models.ManyToManyField(blank=True, related_name='post_likers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='posted_to_user',
            field=models.ForeignKey(default='a6c562cf-9035-43a6-a785-2bfbafcafbd0', on_delete=django.db.models.deletion.CASCADE, related_name='posted_to_user', to='tipsyapp.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='posts_liked',
            field=models.ManyToManyField(blank=True, related_name='posts_liked', to='tipsyapp.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_img',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
