# Generated by Django 3.2 on 2021-04-28 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipsyapp', '0002_auto_20210428_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='checkin_user',
            field=models.ForeignKey(default='608469f6-6b7d-4d5c-8ff2-86502c1d5fe2', on_delete=django.db.models.deletion.CASCADE, related_name='checkin_user', to='tipsyapp.user'),
            preserve_default=False,
        ),
    ]
