# Generated by Django 3.2 on 2021-05-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipsyapp', '0002_post_post_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner_img_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='prof_pic_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='v_banner_img_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='v_prof_pic_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
