# Generated by Django 3.2 on 2021-04-22 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tipsyapp', '0003_auto_20210422_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='posted_to_venue',
        ),
        migrations.CreateModel(
            name='VenuePost',
            fields=[
                ('venue_post_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('venue_post_date', models.DateTimeField(auto_now_add=True)),
                ('venue_post_img', models.URLField(blank=True, max_length=300, null=True)),
                ('venue_post_text', models.TextField(blank=True, max_length=800, null=True)),
                ('posted_to_venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tipsyapp.venue')),
                ('venue_post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_post_author', to=settings.AUTH_USER_MODEL)),
                ('venue_post_likers', models.ManyToManyField(blank=True, related_name='venue_post_likers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['venue_post_date'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='venue_posts_liked',
            field=models.ManyToManyField(blank=True, related_name='venue_posts_liked', to='tipsyapp.VenuePost'),
        ),
    ]
