# Generated by Django 3.2 on 2021-04-28 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipsyapp', '0003_checkin_checkin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='checkedin_venue',
            field=models.ForeignKey(default='5689180c-1894-4d29-96ca-0637fdac8091', on_delete=django.db.models.deletion.CASCADE, related_name='checkedin_venue', to='tipsyapp.venue'),
            preserve_default=False,
        ),
    ]
