# Generated by Django 3.2 on 2021-05-03 20:08

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('tipsyapp', '0003_auto_20210502_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='tags',
        ),
        migrations.AddField(
            model_name='venue',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
