# Generated by Django 3.2 on 2021-04-28 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipsyapp', '0003_alter_checkin_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-post_date']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-join_date']},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['-join_date']},
        ),
    ]
