# Generated by Django 3.2 on 2021-04-24 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipsyapp', '0003_alter_post_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='venue_added_by',
            field=models.ForeignKey(default='ae6819a6-96ee-473e-b706-58b6858366d9', on_delete=django.db.models.deletion.CASCADE, related_name='venue_added_by', to='tipsyapp.user'),
            preserve_default=False,
        ),
    ]
