# Generated by Django 3.2 on 2021-04-20 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipsyapp', '0004_auto_20210420_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='users_followed_by_list',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
