# Generated by Django 3.2 on 2021-04-22 23:20

from django.db import migrations, models
import tipsyapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('tipsyapp', '0004_auto_20210422_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='prof_pic',
            field=models.ImageField(blank=True, null=True, upload_to=tipsyapp.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_type',
            field=models.CharField(choices=[('brewery', 'Brewery'), ('distillery', 'Distillery'), ('winery', 'Winery')], default='brewery', max_length=30),
        ),
    ]
