# Generated by Django 3.2 on 2021-04-25 16:26

from django.db import migrations, models
import tipsyapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('tipsyapp', '0005_alter_venue_prof_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_img_caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_img_file',
            field=models.ImageField(blank=True, null=True, upload_to=tipsyapp.models.post_directory_path),
        ),
        migrations.AddField(
            model_name='user',
            name='prof_pic_img',
            field=models.ImageField(blank=True, null=True, upload_to=tipsyapp.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='venue',
            name='venue_img',
            field=models.ImageField(blank=True, null=True, upload_to=tipsyapp.models.venue_directory_path),
        ),
        migrations.AddField(
            model_name='venue',
            name='venue_img_caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('post_img__isnull', False), ('post_text__isnull', False)), models.Q(('post_img__isnull', True), ('post_text__isnull', False)), models.Q(('post_img__isnull', False), ('post_text__isnull', True)), _connector='OR'), name='tipsyapp_post_post_text_ANDOR_img'),
        ),
    ]
