# Generated by Django 3.2 on 2021-04-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipsyapp', '0005_alter_venue_prof_pic'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('post_img__isnull', False), ('post_text__isnull', False)), models.Q(('post_img__isnull', True), ('post_text__isnull', False)), models.Q(('post_img__isnull', False), ('post_text__isnull', True)), _connector='OR'), name='tipsyapp_post_post_text_ANDOR_img'),
        ),
    ]
