# Generated by Django 3.2 on 2021-05-04 17:03

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('tipsyapp', '0005_auto_20210503_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='street_address',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='tipsyapp.UUIDTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.UniqueConstraint(fields=('venue_name', 'street_address'), name='unique_venue_location'),
        ),
    ]
