# Generated by Django 3.2 on 2021-04-20 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipsyapp', '0005_auto_20210420_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_img', models.URLField(blank=True, max_length=300)),
                ('post_text', models.TextField(blank=True, max_length=800, null=True)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('posted_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipsyapp.venue')),
            ],
            options={
                'ordering': ['post_date'],
            },
        ),
    ]
